/***************************************************/
/************DO NOT MODIFY THIS FILE****************/
/***********IT SHOULD BE AUTO GENERATED*************/
/***************************************************/
#include <string.h>
#define TABLE_EVENT_SIZE 241
#define TABLE_ERROR_SIZE 223
#define _MAX_COMPARE_TIME 1

struct Log_entry
{
	char *code;
	int noR;
	char *message;
};

struct Log_entry log_event_hashed_DE[] =
{
/*  0*/	{"(null)", 0, "(null)"},
/*  1*/	{"(null)", 0, "(null)"},
/*  2*/	{"(null)", 0, "(null)"},
/*  3*/	{"AS400", 0, "Der lokale Medienserver wurde gestartet."},
/*  4*/	{"AS401", 0, "Der lokale Medienserver wurde gestoppt."},
/*  5*/	{"(null)", 0, "(null)"},
/*  6*/	{"(null)", 0, "(null)"},
/*  7*/	{"(null)", 0, "(null)"},
/*  8*/	{"(null)", 0, "(null)"},
/*  9*/	{"V100", 0, "Der Speeddial Speicher wurde durch den Nutzer geleert."},
/* 10*/	{"(null)", 0, "(null)"},
/* 11*/	{"(null)", 0, "(null)"},
/* 12*/	{"(null)", 0, "(null)"},
/* 13*/	{"(null)", 0, "(null)"},
/* 14*/	{"(null)", 0, "(null)"},
/* 15*/	{"(null)", 0, "(null)"},
/* 16*/	{"(null)", 0, "(null)"},
/* 17*/	{"M101", 0, "Das Gerät wurde auf Werkseinstellungen zurückgesetzt."},
/* 18*/	{"M102", 0, "Der Zugang zum Internet wurde gesperrt."},
/* 19*/	{"M103", 0, "Der Zugang zum Internet wurde freigeschaltet."},
/* 20*/	{"(null)", 0, "(null)"},
/* 21*/	{"ME104", 1, "WLAN Router sendet Präfix %s ins LAN"},
/* 22*/	{"(null)", 0, "(null)"},
/* 23*/	{"DEC004", 1, "Das DECT Mobilteil %s hat die Verbindung zur DECT Basis hergestellt"},
/* 24*/	{"(null)", 0, "(null)"},
/* 25*/	{"(null)", 0, "(null)"},
/* 26*/	{"(null)", 0, "(null)"},
/* 27*/	{"(null)", 0, "(null)"},
/* 28*/	{"(null)", 0, "(null)"},
/* 29*/	{"(null)", 0, "(null)"},
/* 30*/	{"FO001", 0, "Verbindung zum FON System (HB) wurde erfolgreich hergestellt // Hotspot Telekom_FON öffentlich nutzbar"},
/* 31*/	{"FO002", 0, "Verbindung zum FON System (HB) wurde verloren. // Hotspot Telekom_FON öffentlich nicht nutzbar"},
/* 32*/	{"FO003", 0, "Der Hotspot Telekom_FON wurde aktiviert"},
/* 33*/	{"FO004", 0, "Der Hotspot Telekom_FON wurde deaktiviert"},
/* 34*/	{"(null)", 0, "(null)"},
/* 35*/	{"IVA101", 1, "%s prüft FW Update"},
/* 36*/	{"IVA102", 2, "Neue Firmware für %s verfügbar: Version %s"},
/* 37*/	{"IVA103", 1, "Keine neue Firmware für %s verfügbar"},
/* 38*/	{"IVA104", 1, "Firmware download an %s wurde gestartet."},
/* 39*/	{"IVA105", 1, "Neue Firmware erfolgreich auf %s installiert"},
/* 40*/	{"P007", 1, "DNSv6 Server %s wurden erfolgreich aktualisiert"},
/* 41*/	{"(null)", 0, "(null)"},
/* 42*/	{"LI001", 0, "HG Anschluss LAN/Link umgeschaltet als ‚LAN’ lokaler Ethernet LAN Anschluss"},
/* 43*/	{"LI002", 0, "HG Anschluss LAN/Link umgeschaltet als ‚Link’ zum Anschluss von externen WAN Modems (z.B. DSLModem)"},
/* 44*/	{"(null)", 0, "(null)"},
/* 45*/	{"ZAB005", 1, "Verbindung zum zentralen Adressbuch: %s wurde erfolgreich aufgebaut."},
/* 46*/	{"(null)", 0, "(null)"},
/* 47*/	{"ZAB007", 2, "Die Synchronisation von %s Kontaktdaten in: %s war erfolgreich."},
/* 48*/	{"ZAB008", 1, "Verbindung zum zentralen Adressbuch: %s wurde getrennt."},
/* 49*/	{"ZAB009", 1, "Anzahl der Telefonbücher wurde erfolgreich auf %s geändert."},
/* 50*/	{"HYB001", 0, "Bonding has started"},
/* 51*/	{"HYB002", 0, "Bonding has stopped"},
/* 52*/	{"HYB003", 0, "Bonding across DSL only"},
/* 53*/	{"HYB004", 0, "Bonding across LTE only"},
/* 54*/	{"HYB005", 0, "Bonding across both DSL and LTE"},
/* 55*/	{"(null)", 0, "(null)"},
/* 56*/	{"(null)", 0, "(null)"},
/* 57*/	{"(null)", 0, "(null)"},
/* 58*/	{"(null)", 0, "(null)"},
/* 59*/	{"(null)", 0, "(null)"},
/* 60*/	{"(null)", 0, "(null)"},
/* 61*/	{"TR102", 1, "%s TR-064 Sitzung beendet."},
/* 62*/	{"AS300", 0, "Der lokale SMB/CIFS Dienst wurde gestartet."},
/* 63*/	{"AS301", 0, "Der lokale SMB/CIFS Dienst wurde gestoppt."},
/* 64*/	{"OAM001", 0, "OAM Modus wurde eingeschaltet"},
/* 65*/	{"OAM002", 0, "OAM Modus wurde beendet"},
/* 66*/	{"OAM003", 0, "OAM remote loopback wurde gestartet"},
/* 67*/	{"OAM004", 0, "OAM remote loopback wurde beendet"},
/* 68*/	{"UM101", 1, "USB-Gerät %s angesteckt."},
/* 69*/	{"UM102", 0, "UMTS-Modem wurde initialisiert"},
/* 70*/	{"UM103", 4, "UMTS Internetverbindung wurde erfolgreich hergestellt. IP-Adresse: %s DNS-Server: %s Gateway: %s Breitband-PoP: %s"},
/* 71*/	{"UM104", 0, "UMTS Internetverbindung wurde getrennt."},
/* 72*/	{"(null)", 0, "(null)"},
/* 73*/	{"(null)", 0, "(null)"},
/* 74*/	{"(null)", 0, "(null)"},
/* 75*/	{"(null)", 0, "(null)"},
/* 76*/	{"(null)", 0, "(null)"},
/* 77*/	{"(null)", 0, "(null)"},
/* 78*/	{"(null)", 0, "(null)"},
/* 79*/	{"(null)", 0, "(null)"},
/* 80*/	{"(null)", 0, "(null)"},
/* 81*/	{"(null)", 0, "(null)"},
/* 82*/	{"A101", 0, "EasySupport wurde aktiviert."},
/* 83*/	{"A102", 0, "EasySupport wurde deaktiviert."},
/* 84*/	{"(null)", 0, "(null)"},
/* 85*/	{"(null)", 0, "(null)"},
/* 86*/	{"(null)", 0, "(null)"},
/* 87*/	{"(null)", 0, "(null)"},
/* 88*/	{"(null)", 0, "(null)"},
/* 89*/	{"(null)", 0, "(null)"},
/* 90*/	{"UD101", 0, "Der Update Vorgang wurde gestartet"},
/* 91*/	{"F101", 1, "Benutzerkonto %s wurde erfolgreich eingerichtet."},
/* 92*/	{"F102", 2, "Benutzerkonto %s wurde bzgl. %s geändert."},
/* 93*/	{"F103", 1, "Benutzerkonto %s wurde erfolgreich entsperrt (nach 60 Minuten-Sperre)."},
/* 94*/	{"F104", 3, "Benutzer %s, %s erfolgreich über %s angemeldet"},
/* 95*/	{"W001", 2, "WLAN-Station abgemeldet: Rechnername: %s, Mac-Adresse: %s"},
/* 96*/	{"F106", 1, "Benutzerkonto %s wurde erfolgreich gelöscht."},
/* 97*/	{"F107", 3, "Hauptordner %s auf Gerät %s am Port %s wurde angelegt."},
/* 98*/	{"F108", 3, "Hauptordner %s auf Gerät %s am Port %s wurde gelöscht."},
/* 99*/	{"F109", 3, "Hauptordner %s auf Gerät %s am Port %s wurde umbenannt."},
/*100*/	{"D003", 0, "DynDNS-Erfolg: Der DynDNS-Anbieter meldet <Erfolgreiche Anmeldung>"},
/*101*/	{"W007", 0, "WLAN wurde auf dem Speedport deaktiviert"},
/*102*/	{"W008", 1, "WLAN SSID wurde geändert %s"},
/*103*/	{"W009", 1, "WLAN Sicherheits-Modus wurde geändert %s"},
/*104*/	{"(null)", 0, "(null)"},
/*105*/	{"(null)", 0, "(null)"},
/*106*/	{"(null)", 0, "(null)"},
/*107*/	{"(null)", 0, "(null)"},
/*108*/	{"(null)", 0, "(null)"},
/*109*/	{"(null)", 0, "(null)"},
/*110*/	{"(null)", 0, "(null)"},
/*111*/	{"(null)", 0, "(null)"},
/*112*/	{"(null)", 0, "(null)"},
/*113*/	{"(null)", 0, "(null)"},
/*114*/	{"(null)", 0, "(null)"},
/*115*/	{"(null)", 0, "(null)"},
/*116*/	{"(null)", 0, "(null)"},
/*117*/	{"G101", 1, "%s Anmeldung erfolgreich."},
/*118*/	{"G102", 1, "%s Abmeldung erfolgreich."},
/*119*/	{"G103", 0, "Konfigurator Sitzung abgelaufen."},
/*120*/	{"G104", 1, "UI Login Versuch von %s mit falschem Passwort."},
/*121*/	{"AS200", 0, "Der lokale FTP-Server wurde gestartet."},
/*122*/	{"AS201", 0, "Der lokale FTP-Server wurde gestoppt."},
/*123*/	{"AS202", 1, "%s Falsches ftp Passwort."},
/*124*/	{"E001", 0, "Doppelter URL-Eintrag in ‘Liste der erlaubten E-Mail-Server’"},
/*125*/	{"E002", 0, "Doppelter Eintrag einer IP-Adresse in ‘Liste der erlaubten E-Mail-Server’"},
/*126*/	{"E003", 0, "Fehlerhafte Schreibweise der IP-Adresse"},
/*127*/	{"E004", 2, "Unerlaubter Verbindungsversuch laut ‘Liste der erlaubten E-Mail-Server’ von %s nach %s"},
/*128*/	{"E005", 0, "‘Liste der erlaubten E-Mail-Server’ wurde geändert"},
/*129*/	{"(null)", 0, "(null)"},
/*130*/	{"(null)", 0, "(null)"},
/*131*/	{"(null)", 0, "(null)"},
/*132*/	{"(null)", 0, "(null)"},
/*133*/	{"(null)", 0, "(null)"},
/*134*/	{"(null)", 0, "(null)"},
/*135*/	{"(null)", 0, "(null)"},
/*136*/	{"(null)", 0, "(null)"},
/*137*/	{"(null)", 0, "(null)"},
/*138*/	{"(null)", 0, "(null)"},
/*139*/	{"(null)", 0, "(null)"},
/*140*/	{"DEC001", 1, "Das DECT Mobilteil %s wurde mit der DECT Basis verbunden"},
/*141*/	{"DEC002", 1, "Die Verbindung des DECT Mobilteil %s zur DECT Basis wurde aufgehoben"},
/*142*/	{"DEC003", 1, "Das DECT Mobilteil %s hat die Verbindung zur DECT Basis verloren"},
/*143*/	{"V016", 4, "Die IP Telefonie Verbindung %s wurde erfolgreich hergestellt. IP-Adresse: %s, DNS-Server: %s, Gateway: %s"},
/*144*/	{"(null)", 0, "(null)"},
/*145*/	{"(null)", 0, "(null)"},
/*146*/	{"(null)", 0, "(null)"},
/*147*/	{"R101", 0, "Info: PADI Paket wurde vom HG gesendet"},
/*148*/	{"R102", 0, "Info: PADO Paket wurde vom HG empfangen"},
/*149*/	{"R103", 0, "Info: PADR Paket wurde vom HG gesendet"},
/*150*/	{"R104", 0, "Info: PADS Paket wurde vom HG empfangen"},
/*151*/	{"R105", 0, "Info: PADT Paket wurde vom HG empfangen"},
/*152*/	{"R106", 0, "Info: PADT Paket wurde vom HG gesendet"},
/*153*/	{"(null)", 0, "(null)"},
/*154*/	{"P001", 1, "Vom Internetanbieter zugewiesene WAN IPv6-Adresse: %s"},
/*155*/	{"P002", 1, "Vom Internetanbieter zugewiesene Gateway-IPv6-Adresse: %s"},
/*156*/	{"(null)", 0, "(null)"},
/*157*/	{"(null)", 0, "(null)"},
/*158*/	{"P005", 1, "Einwahl Router hat Präfix %s von ISP zugewiesen bekommen."},
/*159*/	{"F110", 1, "Das angeschlossene Speichermedium %s ist zu 95% voll"},
/*160*/	{"F111", 1, "Das angeschlossene Speichermedium %s ist zu 100% voll"},
/*161*/	{"F112", 6, "Die Datei-Synch./Backup des Ordners %s auf dem Gerät %s am Port %s mit dem Ziel %s auf dem Gerät %s am Port %s wurde gestartet."},
/*162*/	{"F113", 6, "Die Datei-Synch./Backup des Ordners %s auf dem Gerät %s am Port %s mit dem Ziel %s auf dem Gerät %s am Port %s wurde erfolgreich beendet"},
/*163*/	{"W010", 0, "WLAN Passwort für die Verschlüsselung wurde geändert"},
/*164*/	{"W011", 2, "WLAN-Kanal wurde geändert – Wert: %s, %s"},
/*165*/	{"W012", 1, "WLAN Übertragungsmodus wurde geändert %s"},
/*166*/	{"W013", 0, "WLAN Zeitschaltung aktiviert"},
/*167*/	{"W014", 0, "WLAN Zeitschaltung deaktiviert"},
/*168*/	{"W015", 0, "WLAN durch Zeitschaltung aktiviert"},
/*169*/	{"W016", 0, "WLAN durch Zeitschaltung deaktiviert"},
/*170*/	{"W017", 1, "Der WLAN Kanal wird aufgrund notwendiger Anpassungen zur Übertragungsverbesserung gewechselt (bisher Kanal %s)"},
/*171*/	{"W018", 1, "Der WLAN Kanal wurde aufgrund notwendiger Anpassungen zur Übertragungsverbesserung auf den Kanal %s gewechselt"},
/*172*/	{"W019", 2, "WLAN-Anmeldung an 2.4 GHz Frequenzband erfolgreich: Rechnername: %s, Mac-Adresse: %s"},
/*173*/	{"S101", 0, "Die Konfiguration des Gerätes wurde erfolgreich gespeichert."},
/*174*/	{"S102", 0, "Die Konfiguration des Gerätes wurde erfolgreich eingelesen."},
/*175*/	{"(null)", 0, "(null)"},
/*176*/	{"(null)", 0, "(null)"},
/*177*/	{"(null)", 0, "(null)"},
/*178*/	{"(null)", 0, "(null)"},
/*179*/	{"FW101", 1, "DoS (Denial of Service) Angriff %s wurde entdeckt."},
/*180*/	{"TR101", 1, "%s TR-064 Sitzung gestartet."},
/*181*/	{"AS101", 0, "Konfigurations-Service wird kontaktiert"},
/*182*/	{"AS102", 0, "Zugangsdaten wurden vom Konfigurations-Service übermittelt"},
/*183*/	{"AS103", 0, "Internet-Telefonie Daten wurden vom Konfigurations-Service übermittelt"},
/*184*/	{"(null)", 0, "(null)"},
/*185*/	{"NT101", 0, "Die IPv6 Systemzeit wurde erfolgreich aktualisiert"},
/*186*/	{"(null)", 0, "(null)"},
/*187*/	{"(null)", 0, "(null)"},
/*188*/	{"(null)", 0, "(null)"},
/*189*/	{"(null)", 0, "(null)"},
/*190*/	{"(null)", 0, "(null)"},
/*191*/	{"(null)", 0, "(null)"},
/*192*/	{"(null)", 0, "(null)"},
/*193*/	{"(null)", 0, "(null)"},
/*194*/	{"(null)", 0, "(null)"},
/*195*/	{"(null)", 0, "(null)"},
/*196*/	{"(null)", 0, "(null)"},
/*197*/	{"(null)", 0, "(null)"},
/*198*/	{"(null)", 0, "(null)"},
/*199*/	{"T101", 0, "Die Systemzeit wurde erfolgreich aktualisiert"},
/*200*/	{"(null)", 0, "(null)"},
/*201*/	{"(null)", 0, "(null)"},
/*202*/	{"H001", 10, "DHCP ist aktiv: %s %s %s %s %s %s %s %s %s %s"},
/*203*/	{"H002", 0, "DHCP wurde deaktiviert"},
/*204*/	{"A103", 0, "Konfigurations-Service wird kontaktiert"},
/*205*/	{"A104", 0, "Zugangsdaten wurden vom Konfigurations-Service übermittelt"},
/*206*/	{"A105", 0, "Internet-Telefonie Daten wurden vom Konfigurations-Service übermittelt"},
/*207*/	{"A106", 1, "Firmware Update auf Version %s wurde erfolgreich durchgeführt."},
/*208*/	{"A107", 0, "Konfiguration fehlgeschlagen."},
/*209*/	{"(null)", 0, "(null)"},
/*210*/	{"(null)", 0, "(null)"},
/*211*/	{"(null)", 0, "(null)"},
/*212*/	{"UD102", 1, "Der Update Vorgang auf Version %s war erfolgreich."},
/*213*/	{"(null)", 0, "(null)"},
/*214*/	{"(null)", 0, "(null)"},
/*215*/	{"(null)", 0, "(null)"},
/*216*/	{"F105", 2, "Lokaler Benutzer %s, %s erfolgreich abgemeldet"},
/*217*/	{"(null)", 0, "(null)"},
/*218*/	{"W201", 1, "WPS wurde gestartet mit %s"},
/*219*/	{"W202", 1, "WPS Aktion %s"},
/*220*/	{"DH101", 3, "DHCP ist aktiv: %s %s %s"},
/*221*/	{"W006", 0, "WLAN wurde auf dem Speedport aktiviert"},
/*222*/	{"(null)", 0, "(null)"},
/*223*/	{"(null)", 0, "(null)"},
/*224*/	{"(null)", 0, "(null)"},
/*225*/	{"U101", 1, "USB Gerät %s wurde angeschlossen."},
/*226*/	{"U102", 1, "USB Gerät %s wurde entfernt."},
/*227*/	{"(null)", 0, "(null)"},
/*228*/	{"B101", 0, "Das Gerät ist neu eingeschaltet worden."},
/*229*/	{"(null)", 0, "(null)"},
/*230*/	{"B103", 0, "Es wurde ein Reboot ausgelöst."},
/*231*/	{"(null)", 0, "(null)"},
/*232*/	{"W020", 2, "WLAN-Anmeldung an 5 GHz Frequenzband erfolgreich: Rechnername: %s, Mac-Adresse: %s"},
/*233*/	{"(null)", 0, "(null)"},
/*234*/	{"(null)", 0, "(null)"},
/*235*/	{"(null)", 0, "(null)"},
/*236*/	{"(null)", 0, "(null)"},
/*237*/	{"(null)", 0, "(null)"},
/*238*/	{"(null)", 0, "(null)"},
/*239*/	{"(null)", 0, "(null)"},
/*240*/	{"S009", 0, "Schwerwiegender Fehler beim Import. Das Speedport wurde auf Werkseinstellungen zurückgesetzt."},
};

struct Log_entry log_error_hashed_DE[] =
{
/*  0*/	{"R001-56-0004", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <wrong access attributes>"},
/*  1*/	{"R001-56-0005", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <VIP not available>"},
/*  2*/	{"R001-56-0006", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <radius server not responding>"},
/*  3*/	{"R001-56-0007", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <service not supported>"},
/*  4*/	{"R001-56-0008", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <class to long>"},
/*  5*/	{"R001-56-0009", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <no domain>"},
/*  6*/	{"(null)", 0, "(null)"},
/*  7*/	{"(null)", 0, "(null)"},
/*  8*/	{"AS010", 0, "Firmware Download fehlgeschlagen."},
/*  9*/	{"AS011", 0, "Firmware Datei beschädigt."},
/* 10*/	{"V001", 1, "Anmeldung der DSL-Telefonnummer %s war nicht erfolgreich. Ursache: DNS-Fehler"},
/* 11*/	{"V002", 2, "Anmeldung der DSL-Telefonnummer %s war nicht erfolgreich. Gegenstelle meldet Ursache: %s"},
/* 12*/	{"V003", 0, "Es ist ein allgemeiner Fehler bei der IPTelefonie aufgetreten: Diese Aktion ist nicht erlaubt (SIP Fehlercode 488)"},
/* 13*/	{"V004", 1, "Anmeldung der DSL-Telefonnummer %s war nicht erfolgreich. Ursache: Gegenstelle antwortet nicht. Zeitüberschreitung."},
/* 14*/	{"V005", 2, "Abmeldung der DSL-Telefonnummer %s war nicht erfolgreich. Gegenstelle meldet Ursache: %s"},
/* 15*/	{"V006", 2, "IP-Telefonie mit %s war nicht erfolgreich. Ursache: %s"},
/* 16*/	{"V007", 0, "Es ist ein allgemeiner Fehler bei der IPTelefonie aufgetreten: Diese Aktion ist nicht möglich. (SIP Fehlercode 403)"},
/* 17*/	{"V008", 0, "Es ist ein allgemeiner Fehler bei der IPTelefonie aufgetreten: Der angerufene Teilnehmer wurde nicht gefunden (SIP Fehlercode 404)"},
/* 18*/	{"V009", 0, "Es ist ein allgemeiner Fehler bei der IPTelefonie aufgetreten: Die gewünschte SIP Funktionalität wird nicht unterstützt (SIP Fehlercode 405)"},
/* 19*/	{"T102", 0, "Die Systemzeit konnte nicht aktualisiert werden."},
/* 20*/	{"T103", 0, "Keine Antwort vom Timeserver."},
/* 21*/	{"AS007", 0, "Der Konfigurations-Server antwortet nicht."},
/* 22*/	{"AS008", 0, "Internet-Telefonie Daten konnen nicht ermittelt werden."},
/* 23*/	{"AS009", 0, "Internet-Telefonie ist nicht gebucht."},
/* 24*/	{"F114", 7, "Die Datei-Synch./Backup des Ordners %s auf dem Gerät %s am Port %s mit dem Ziel %s auf dem Gerät %s am Port %s ist gescheitert %s."},
/* 25*/	{"(null)", 0, "(null)"},
/* 26*/	{"(null)", 0, "(null)"},
/* 27*/	{"R001-56-0012", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <test user>"},
/* 28*/	{"R001-56-0013", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <user wrong domain>"},
/* 29*/	{"R001-56-0014", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <bad form>"},
/* 30*/	{"R001-56-0015", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <not in session>"},
/* 31*/	{"R001-56-0016", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <domain access disabled>"},
/* 32*/	{"R001-56-0017", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <authorization disabled>"},
/* 33*/	{"R001-56-0018", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <port limit exceeded>"},
/* 34*/	{"R001-56-0019", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <you are not allowed to connect>"},
/* 35*/	{"(null)", 0, "(null)"},
/* 36*/	{"(null)", 0, "(null)"},
/* 37*/	{"UD103", 2, "Der Update Vorgang auf Version %s war nicht erfolgreich: %s"},
/* 38*/	{"V010", 0, "Die angerufene Nummer ist unvollständig (SIP Fehlercode 484)"},
/* 39*/	{"V011", 0, "Es ist ein allgemeiner Fehler bei der IPTelefonie aufgetreten: Diese Aktion ist nicht möglich (SIP Fehlercode 491)"},
/* 40*/	{"V012", 0, "Es ist ein allgemeiner Fehler bei der IPTelefonie aufgetreten: Es ist ein Serverfehler aufgetreten (SIP Fehlercode 500)"},
/* 41*/	{"V013", 0, "Es ist ein allgemeiner Fehler bei der IPTelefonie aufgetreten: Es ist ein Serverfehler aufgetreten (SIP Fehlercode 503)"},
/* 42*/	{"(null)", 0, "(null)"},
/* 43*/	{"F001", 1, "Benutzerkonto %s wurde nach mehr als 5 erfolglosen lokalen Anmeldeversuchen für 60 Minuten gesperrt."},
/* 44*/	{"F002", 1, "Benutzerkonto %s wurde nach mehr als 5 erfolglosen externen Anmeldeversuchen für 60 Minuten gesperrt."},
/* 45*/	{"F003", 3, "Anmeldung des Benutzers %s, %s über %s nicht erfolgreich."},
/* 46*/	{"V018", 0, "PPP-Anmeldung beim IP-Telefonie-Anbieter ist fehlgeschlagen."},
/* 47*/	{"V019", 0, "PPP-Aushandlung für IP-Telefonie ist fehlgeschlagen."},
/* 48*/	{"(null)", 0, "(null)"},
/* 49*/	{"(null)", 0, "(null)"},
/* 50*/	{"S010", 0, "Die angegebene Datei ist zu groß."},
/* 51*/	{"(null)", 0, "(null)"},
/* 52*/	{"(null)", 0, "(null)"},
/* 53*/	{"(null)", 0, "(null)"},
/* 54*/	{"R001-56-0020", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <unknown dynamic ip address>"},
/* 55*/	{"R001-56-0021", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <no valid ip address>"},
/* 56*/	{"R001-56-0022", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <Der Mitbenutzer-Zugang wurde vom Hauptnutzer gesperrt>"},
/* 57*/	{"R001-56-0023", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <Ihre Zugangsdaten wurden gesperrt>."},
/* 58*/	{"R001-56-0024", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <no valid service level>"},
/* 59*/	{"R001-56-0025", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <Mit diesen Zugangsdaten ist an diesem Anschluss kein Verbindungsaufbau möglich>"},
/* 60*/	{"R001-56-0026", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <Es ist ein Fehler bei der Identifizierung Ihrer Zugangsdaten aufgetreten>"},
/* 61*/	{"R001-56-0027", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <you are not allowed to connect right now>"},
/* 62*/	{"R001-56-0028", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <Ihr T-Online Zugang wurde gesperrt>."},
/* 63*/	{"R001-56-0029", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <authorization not available>"},
/* 64*/	{"(null)", 0, "(null)"},
/* 65*/	{"(null)", 0, "(null)"},
/* 66*/	{"(null)", 0, "(null)"},
/* 67*/	{"V020", 0, "PPP-Aushandlung für IP-Telefonie ist fehlgeschlagen: Testschleife gefunden."},
/* 68*/	{"V021", 1, "Zeitüberschreitung bei der PPP-Aushandlung für IP-Telefonie. (%s)"},
/* 69*/	{"(null)", 0, "(null)"},
/* 70*/	{"(null)", 0, "(null)"},
/* 71*/	{"(null)", 0, "(null)"},
/* 72*/	{"(null)", 0, "(null)"},
/* 73*/	{"(null)", 0, "(null)"},
/* 74*/	{"(null)", 0, "(null)"},
/* 75*/	{"(null)", 0, "(null)"},
/* 76*/	{"(null)", 0, "(null)"},
/* 77*/	{"(null)", 0, "(null)"},
/* 78*/	{"(null)", 0, "(null)"},
/* 79*/	{"A001", 0, "Der Konfigurations-Service konnte nicht erreicht werden."},
/* 80*/	{"A002", 0, "Der Konfigurations-Service verweigert den Zugriff."},
/* 81*/	{"A003", 0, "Ungültiges Zertifikat am Konfigurations-Service."},
/* 82*/	{"A004", 0, "Fehlermeldung des Konfigurations-Services."},
/* 83*/	{"R001-56-0030", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <Mit den verwendeten Zugangsdaten besteht bereits eine Verbindung>"},
/* 84*/	{"R001-56-0031", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <user name bad form>"},
/* 85*/	{"R001-56-0032", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <concurrent dial in/out>"},
/* 86*/	{"R001-56-0033", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <link limit exceeded>"},
/* 87*/	{"R001-56-0034", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <Der Zugang ins Internet ist nicht möglich, da der genutzte T-Online Tarif nicht zu dem bestehenden T-DSL Anschluss passt>"},
/* 88*/	{"R001-56-0035", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <domain access revoked>"},
/* 89*/	{"(null)", 0, "(null)"},
/* 90*/	{"(null)", 0, "(null)"},
/* 91*/	{"(null)", 0, "(null)"},
/* 92*/	{"(null)", 0, "(null)"},
/* 93*/	{"IVA001", 1, "Firmware Installation auf %s nicht erfolgreich"},
/* 94*/	{"W003", 2, "WLAN Anmeldung ist gescheitert: Association-Fehler. Datenrate nicht kompatibel. Rechnername: %s, Mac-Adresse: %s"},
/* 95*/	{"W004", 2, "WLAN-Anmeldung ist gescheitert: Association-Fehler. Mac-Adresse wird nicht zugelassen. Rechnername: %s, Mac-Adresse: %s"},
/* 96*/	{"W005", 2, "WLAN-Anmeldung ist gescheitert: Autorisierung fehlgeschlagen. Rechnername: %s, Mac-Adresse: %s"},
/* 97*/	{"(null)", 0, "(null)"},
/* 98*/	{"(null)", 0, "(null)"},
/* 99*/	{"(null)", 0, "(null)"},
/*100*/	{"(null)", 0, "(null)"},
/*101*/	{"(null)", 0, "(null)"},
/*102*/	{"D001", 0, "DynDNS-Fehler: Der angegebene Domainname kann nicht aufgelöst werden."},
/*103*/	{"D002", 1, "DynDNS-Fehler: Der DynDNS-Anbieter meldet Fehler %s"},
/*104*/	{"(null)", 0, "(null)"},
/*105*/	{"(null)", 0, "(null)"},
/*106*/	{"(null)", 0, "(null)"},
/*107*/	{"A010", 0, "Firmware Download fehlgeschlagen."},
/*108*/	{"A011", 0, "Firmware Datei beschädigt."},
/*109*/	{"A012", 0, "Die persönlichen Zugangsdaten konnten nicht ermittelt werden."},
/*110*/	{"(null)", 0, "(null)"},
/*111*/	{"(null)", 0, "(null)"},
/*112*/	{"(null)", 0, "(null)"},
/*113*/	{"ZAB001", 1, "Authentifizierung des Online-Adressbuchs: %s ist fehlgeschlagen. Request-Header-Element konnte nicht übermittelt werden."},
/*114*/	{"ZAB002", 1, "Anmeldung des Online-Adressbuchs: %s ist fehlgeschlagen. Benutzername oder Passwort ist nicht korrekt."},
/*115*/	{"ZAB003", 1, "Anmeldung des Online-Adressbuchs mit den verwendeten Zugangsdaten für Telefonbuch: %s nicht möglich. Keine Berechtigung."},
/*116*/	{"ZAB004", 0, "Verbindung zum Online-Adressbuch konnte nicht aufgebaut werden. Server nicht erreichbar."},
/*117*/	{"(null)", 0, "(null)"},
/*118*/	{"A005", 0, "Ungültige Meldung des Konfigurations-Services."},
/*119*/	{"A006", 0, "Die Verbindung zum Konfigurations-Server ist abgebrochen."},
/*120*/	{"A007", 0, "Der Konfigurations-Server antwortet nicht."},
/*121*/	{"A008", 0, "DSL-Telefonie Daten können nicht ermittelt werden."},
/*122*/	{"A009", 0, "DSL-Telefonie ist nicht gebucht."},
/*123*/	{"(null)", 0, "(null)"},
/*124*/	{"(null)", 0, "(null)"},
/*125*/	{"(null)", 0, "(null)"},
/*126*/	{"(null)", 0, "(null)"},
/*127*/	{"(null)", 0, "(null)"},
/*128*/	{"R001", 0, "Anmeldung beim Internetanbieter ist fehlgeschlagen."},
/*129*/	{"R002", 0, "Die Internetverbindung kann nicht aufgebaut werden, da die Tarifprüfung aktiviert ist und das aktuelle Datum nicht bekannt ist."},
/*130*/	{"R003", 0, "Die Internetverbindung wird abgebaut, da die Tarifprüfung aktiviert ist und das aktuelle Datum nicht bekannt ist."},
/*131*/	{"R004", 0, "Die Internetverbindung wird kurz unterbrochen, um der Zwangstrennung durch den Anbieter zuvorzukommen."},
/*132*/	{"R005", 0, "Die maximale Anzahl der Portfreigabe-Regeln wurde erreicht."},
/*133*/	{"R006", 0, "DSL antwortet nicht (keine DSLSynchronisierung)."},
/*134*/	{"R007", 0, "DSL ist verfügbar (DSLSynchronisierung besteht)."},
/*135*/	{"R008", 0, "DSL-Synchronisation beginnt (Training)."},
/*136*/	{"R009", 0, "Internetverbindung wurde getrennt."},
/*137*/	{"(null)", 0, "(null)"},
/*138*/	{"(null)", 0, "(null)"},
/*139*/	{"(null)", 0, "(null)"},
/*140*/	{"(null)", 0, "(null)"},
/*141*/	{"(null)", 0, "(null)"},
/*142*/	{"(null)", 0, "(null)"},
/*143*/	{"UP001", 0, "UMTS-Modem-Fehler Abbruch: ‚kein Trägersignal’"},
/*144*/	{"(null)", 0, "(null)"},
/*145*/	{"(null)", 0, "(null)"},
/*146*/	{"(null)", 0, "(null)"},
/*147*/	{"OAM1001", 0, "OAM Link fault"},
/*148*/	{"OAM1002", 0, "OAM Dying gasp"},
/*149*/	{"OAM1003", 0, "OAM Critical event"},
/*150*/	{"(null)", 0, "(null)"},
/*151*/	{"U001", 1, "Der USB-Massenspeicher %s enthält kein unterstütztes Dateisystem oder hat eine ungültige Partitionstabelle."},
/*152*/	{"U002", 3, "Der angeschlossene USB-Massenspeicher %s, %s kann leider nicht verwendet werden %s."},
/*153*/	{"ZAB006", 1, "Max. Anzahl an Kontakten erreicht. Es konnten nicht alle Kontakte synchronisiert werden. (%s)."},
/*154*/	{"(null)", 0, "(null)"},
/*155*/	{"(null)", 0, "(null)"},
/*156*/	{"R010", 0, "Internetverbindung wurde hergestellt."},
/*157*/	{"R011", 0, "PPP-Aushandlung ist fehlgeschlagen."},
/*158*/	{"R012", 0, "PPP-Aushandlung fehlgeschlagen: Testschleife gefunden."},
/*159*/	{"R013", 0, "PPPoE-Fehler: DSL-Synchronisierung verloren."},
/*160*/	{"R014", 1, "PPPoE-Fehler: Falscher Parameter. (%s)"},
/*161*/	{"R015", 1, "PPPoE-Fehler: Falscher Dienst-Name. (%s)"},
/*162*/	{"R016", 1, "PPPoE-Fehler: Illegales Paket vom PPPoE-Server. (%s)"},
/*163*/	{"R017", 1, "PPPoE-Fehler: PPPoE-Server meldet einen Systemfehler: (%s)"},
/*164*/	{"R018", 1, "PPPoE-Fehler: PPPoE-Server meldet ein Problem. (%s)"},
/*165*/	{"R019", 1, "PPPoE-Fehler: Unbekannter Fehler. (%s)"},
/*166*/	{"(null)", 0, "(null)"},
/*167*/	{"(null)", 0, "(null)"},
/*168*/	{"(null)", 0, "(null)"},
/*169*/	{"(null)", 0, "(null)"},
/*170*/	{"R010-1", 0, "Internetverbindung für die Automatische Konfiguration hergestellt."},
/*171*/	{"R010-2", 0, "Internetverbindung für die Automatische Konfiguration hergestellt."},
/*172*/	{"(null)", 0, "(null)"},
/*173*/	{"(null)", 0, "(null)"},
/*174*/	{"(null)", 0, "(null)"},
/*175*/	{"(null)", 0, "(null)"},
/*176*/	{"(null)", 0, "(null)"},
/*177*/	{"(null)", 0, "(null)"},
/*178*/	{"(null)", 0, "(null)"},
/*179*/	{"(null)", 0, "(null)"},
/*180*/	{"(null)", 0, "(null)"},
/*181*/	{"(null)", 0, "(null)"},
/*182*/	{"(null)", 0, "(null)"},
/*183*/	{"(null)", 0, "(null)"},
/*184*/	{"(null)", 0, "(null)"},
/*185*/	{"R020", 1, "PPPoE-Fehler: Zeitüberschreitung. (%s)"},
/*186*/	{"R021", 0, "Verbindung getrennt: Die Gegenstelle beantwortet keine LCP-Echo-Anfragen."},
/*187*/	{"R022", 1, "Die vom Internetanbieter zugewiesene Gateway-IP-Adresse: %s"},
/*188*/	{"R023", 1, "Zeitüberschreitung bei der PPPAushandlung. (%s)"},
/*189*/	{"NT102", 0, "Die IPv6 Systemzeit konnte nicht aktualisiert werden."},
/*190*/	{"NT103", 0, "Keine Antwort vom IPv6 Timeserver."},
/*191*/	{"(null)", 0, "(null)"},
/*192*/	{"(null)", 0, "(null)"},
/*193*/	{"(null)", 0, "(null)"},
/*194*/	{"(null)", 0, "(null)"},
/*195*/	{"(null)", 0, "(null)"},
/*196*/	{"P003", 0, "IPv6 Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: IPv6: <no free ip address>"},
/*197*/	{"P004", 0, "IPv6 Anmeldung beim Internetanbieter ist fehlgeschlagen."},
/*198*/	{"(null)", 0, "(null)"},
/*199*/	{"P006", 1, "Router hat kein Präfix von ISP erhalten. Fehler: %s"},
/*200*/	{"(null)", 0, "(null)"},
/*201*/	{"P008", 2, "DNSv6-Fehler: Der angegebene Domainname kann nicht von %s aufgelöst werden. Fehler: %s"},
/*202*/	{"(null)", 0, "(null)"},
/*203*/	{"AS001", 0, "Der Konfigurations-Service konnte nicht erreicht werden."},
/*204*/	{"AS002", 0, "Der Konfigurations-Service verweigert den Zugriff."},
/*205*/	{"AS003", 0, "Ungültiges Zertifikat am Konfiguratons-Service."},
/*206*/	{"AS004", 0, "Fehlermeldung des Konfigurations-Service."},
/*207*/	{"AS005", 0, "Ungültige Meldung des Konfigurations-Service."},
/*208*/	{"AS006", 0, "Die Verbindung zum Konfigurations-Server ist abgebrochen."},
/*209*/	{"H003", 0, "DHCP IP-Address-Vergabe gescheitert"},
/*210*/	{"S001", 0, "Das Import-Kennwort ist falsch."},
/*211*/	{"S002", 0, "Die angegebene Datei ist keine gültige Import-Datei."},
/*212*/	{"S003", 0, "Die Import-Datei enthält eine Landeseinstellung, die auf diesem Speedport nicht importiert werden kann."},
/*213*/	{"S004", 0, "Die Import-Datei ist nicht vorhanden oder zu klein."},
/*214*/	{"S005", 0, "Die Import-Datei passt nicht zu der aktuellen Firmware-Version."},
/*215*/	{"S006", 0, "Die Import-Datei passt nicht zu diesem Gerätetyp dem Speedport."},
/*216*/	{"S007", 0, "Die Import-Datei passt nicht zu dieser Geräte-Variante dem Speedport."},
/*217*/	{"S008", 0, "Es ist ein nicht näher spezifizierter Fehler aufgetreten."},
/*218*/	{"(null)", 0, "(null)"},
/*219*/	{"(null)", 0, "(null)"},
/*220*/	{"R001-56-0001", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <Radius Fehlermeldung>"},
/*221*/	{"R001-56-0002", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <access over this NAS not allowed>"},
/*222*/	{"R001-56-0003", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <no free ip address>"},
};

struct Log_entry log_event_hashed_EN[] =
{
/*  0*/	{"(null)", 0, "(null)"},
/*  1*/	{"(null)", 0, "(null)"},
/*  2*/	{"(null)", 0, "(null)"},
/*  3*/	{"AS400", 0, "The local media server is started."},
/*  4*/	{"AS401", 0, "The local media server is stopped."},
/*  5*/	{"(null)", 0, "(null)"},
/*  6*/	{"(null)", 0, "(null)"},
/*  7*/	{"(null)", 0, "(null)"},
/*  8*/	{"(null)", 0, "(null)"},
/*  9*/	{"V100", 0, "Der Speeddial Speicher wurde durch den Nutzer geleert."},
/* 10*/	{"(null)", 0, "(null)"},
/* 11*/	{"(null)", 0, "(null)"},
/* 12*/	{"(null)", 0, "(null)"},
/* 13*/	{"(null)", 0, "(null)"},
/* 14*/	{"(null)", 0, "(null)"},
/* 15*/	{"(null)", 0, "(null)"},
/* 16*/	{"(null)", 0, "(null)"},
/* 17*/	{"M101", 0, "Das Gerät wurde auf Werkseinstellungen zurückgesetzt."},
/* 18*/	{"M102", 0, "Der Zugang zum Internet wurde gesperrt."},
/* 19*/	{"M103", 0, "Der Zugang zum Internet wurde freigeschaltet."},
/* 20*/	{"(null)", 0, "(null)"},
/* 21*/	{"ME104", 1, "WLAN Router sendet Präfix %s ins LAN"},
/* 22*/	{"(null)", 0, "(null)"},
/* 23*/	{"DEC004", 1, "Das DECT Mobilteil %s hat die Verbindung zur DECT Basis hergestellt"},
/* 24*/	{"(null)", 0, "(null)"},
/* 25*/	{"(null)", 0, "(null)"},
/* 26*/	{"(null)", 0, "(null)"},
/* 27*/	{"(null)", 0, "(null)"},
/* 28*/	{"(null)", 0, "(null)"},
/* 29*/	{"(null)", 0, "(null)"},
/* 30*/	{"FO001", 0, "Verbindung zum FON System (HB) wurde erfolgreich hergestellt // Hotspot Telekom_FON öffentlich nutzbar"},
/* 31*/	{"FO002", 0, "Verbindung zum FON System (HB) wurde verloren. // Hotspot Telekom_FON öffentlich nicht nutzbar"},
/* 32*/	{"FO003", 0, "Der Hotspot Telekom_FON wurde aktiviert"},
/* 33*/	{"FO004", 0, "Der Hotspot Telekom_FON wurde deaktiviert"},
/* 34*/	{"(null)", 0, "(null)"},
/* 35*/	{"IVA101", 1, "%s prüft FW Update"},
/* 36*/	{"IVA102", 2, "Neue Firmware für %s verfügbar: Version %s"},
/* 37*/	{"IVA103", 1, "Keine neue Firmware für %s verfügbar"},
/* 38*/	{"IVA104", 1, "Firmware download an %s wurde gestartet."},
/* 39*/	{"IVA105", 1, "Neue Firmware erfolgreich auf %s installiert"},
/* 40*/	{"P007", 1, "DNSv6 Server %s wurden erfolgreich aktualisiert"},
/* 41*/	{"(null)", 0, "(null)"},
/* 42*/	{"LI001", 0, "HG Anschluss LAN/Link umgeschaltet als ‚LAN’ lokaler Ethernet LAN Anschluss"},
/* 43*/	{"LI002", 0, "HG Anschluss LAN/Link umgeschaltet als ‚Link’ zum Anschluss von externen WAN Modems (z.B. DSLModem)"},
/* 44*/	{"(null)", 0, "(null)"},
/* 45*/	{"ZAB005", 1, "Verbindung zum zentralen Adressbuch: %s wurde erfolgreich aufgebaut."},
/* 46*/	{"(null)", 0, "(null)"},
/* 47*/	{"ZAB007", 2, "Die Synchronisation von %s Kontaktdaten in: %s war erfolgreich."},
/* 48*/	{"ZAB008", 1, "Verbindung zum zentralen Adressbuch: %s wurde getrennt."},
/* 49*/	{"ZAB009", 1, "Anzahl der Telefonbücher wurde erfolgreich auf %s geändert."},
/* 50*/	{"HYB001", 0, "Bonding has started"},
/* 51*/	{"HYB002", 0, "Bonding has stopped"},
/* 52*/	{"HYB003", 0, "Bonding across DSL only"},
/* 53*/	{"HYB004", 0, "Bonding across LTE only"},
/* 54*/	{"HYB005", 0, "Bonding across both DSL and LTE"},
/* 55*/	{"(null)", 0, "(null)"},
/* 56*/	{"(null)", 0, "(null)"},
/* 57*/	{"(null)", 0, "(null)"},
/* 58*/	{"(null)", 0, "(null)"},
/* 59*/	{"(null)", 0, "(null)"},
/* 60*/	{"(null)", 0, "(null)"},
/* 61*/	{"TR102", 1, "%s TR-064 Sitzung beendet."},
/* 62*/	{"AS300", 0, "The local SMB / CIFS service is started."},
/* 63*/	{"AS301", 0, "The local SMB / CIFS service was stopped."},
/* 64*/	{"OAM001", 0, "OAM Modus wurde eingeschaltet"},
/* 65*/	{"OAM002", 0, "OAM Modus wurde beendet"},
/* 66*/	{"OAM003", 0, "OAM remote loopback wurde gestartet"},
/* 67*/	{"OAM004", 0, "OAM remote loopback wurde beendet"},
/* 68*/	{"UM101", 1, "USB-Gerät %s angesteckt."},
/* 69*/	{"UM102", 0, "UMTS-Modem wurde initialisiert"},
/* 70*/	{"UM103", 4, "UMTS Internetverbindung wurde erfolgreich hergestellt. IP-Adresse: %s DNS-Server: %s Gateway: %s Breitband-PoP: %s"},
/* 71*/	{"UM104", 0, "UMTS Internetverbindung wurde getrennt."},
/* 72*/	{"(null)", 0, "(null)"},
/* 73*/	{"(null)", 0, "(null)"},
/* 74*/	{"(null)", 0, "(null)"},
/* 75*/	{"(null)", 0, "(null)"},
/* 76*/	{"(null)", 0, "(null)"},
/* 77*/	{"(null)", 0, "(null)"},
/* 78*/	{"(null)", 0, "(null)"},
/* 79*/	{"(null)", 0, "(null)"},
/* 80*/	{"(null)", 0, "(null)"},
/* 81*/	{"(null)", 0, "(null)"},
/* 82*/	{"A101", 0, "Easy support has been enabled."},
/* 83*/	{"A102", 0, "Easy support has been disabled."},
/* 84*/	{"(null)", 0, "(null)"},
/* 85*/	{"(null)", 0, "(null)"},
/* 86*/	{"(null)", 0, "(null)"},
/* 87*/	{"(null)", 0, "(null)"},
/* 88*/	{"(null)", 0, "(null)"},
/* 89*/	{"(null)", 0, "(null)"},
/* 90*/	{"UD101", 0, "Der Update Vorgang wurde gestartet"},
/* 91*/	{"F101", 1, "Benutzerkonto %s wurde erfolgreich eingerichtet."},
/* 92*/	{"F102", 2, "Benutzerkonto %s wurde bzgl. %s geändert."},
/* 93*/	{"F103", 1, "Benutzerkonto %s wurde erfolgreich entsperrt (nach 60 Minuten-Sperre)."},
/* 94*/	{"F104", 3, "Benutzer %s, %s erfolgreich über %s angemeldet"},
/* 95*/	{"W001", 2, "WLAN-Station abgemeldet: Rechnername: %s, Mac-Adresse: %s"},
/* 96*/	{"F106", 1, "Benutzerkonto %s wurde erfolgreich gelöscht."},
/* 97*/	{"F107", 3, "Hauptordner %s auf Gerät %s am Port %s wurde angelegt."},
/* 98*/	{"F108", 3, "Hauptordner %s auf Gerät %s am Port %s wurde gelöscht."},
/* 99*/	{"F109", 3, "Hauptordner %s auf Gerät %s am Port %s wurde umbenannt."},
/*100*/	{"D003", 0, "DynDNS-Erfolg: Der DynDNS-Anbieter meldet <Erfolgreiche Anmeldung>"},
/*101*/	{"W007", 0, "WLAN wurde auf dem Speedport deaktiviert"},
/*102*/	{"W008", 1, "WLAN SSID wurde geändert %s"},
/*103*/	{"W009", 1, "WLAN Sicherheits-Modus wurde geändert %s"},
/*104*/	{"(null)", 0, "(null)"},
/*105*/	{"(null)", 0, "(null)"},
/*106*/	{"(null)", 0, "(null)"},
/*107*/	{"(null)", 0, "(null)"},
/*108*/	{"(null)", 0, "(null)"},
/*109*/	{"(null)", 0, "(null)"},
/*110*/	{"(null)", 0, "(null)"},
/*111*/	{"(null)", 0, "(null)"},
/*112*/	{"(null)", 0, "(null)"},
/*113*/	{"(null)", 0, "(null)"},
/*114*/	{"(null)", 0, "(null)"},
/*115*/	{"(null)", 0, "(null)"},
/*116*/	{"(null)", 0, "(null)"},
/*117*/	{"G101", 1, "%s Anmeldung erfolgreich."},
/*118*/	{"G102", 1, "%s Abmeldung erfolgreich."},
/*119*/	{"G103", 0, "Konfigurator Sitzung abgelaufen."},
/*120*/	{"G104", 1, "UI Login Versuch von %s mit falschem Passwort."},
/*121*/	{"AS200", 0, "Local FTP server has been started."},
/*122*/	{"AS201", 0, "Local FTP server has been stopped."},
/*123*/	{"AS202", 1, "%s Wrong FTP password."},
/*124*/	{"E001", 0, "Doppelter URL-Eintrag in ‘Liste der erlaubten E-Mail-Server’"},
/*125*/	{"E002", 0, "Doppelter Eintrag einer IP-Adresse in ‘Liste der erlaubten E-Mail-Server’"},
/*126*/	{"E003", 0, "Fehlerhafte Schreibweise der IP-Adresse"},
/*127*/	{"E004", 2, "Unerlaubter Verbindungsversuch laut ‘Liste der erlaubten E-Mail-Server’ von %s nach %s"},
/*128*/	{"E005", 0, "‘Liste der erlaubten E-Mail-Server’ wurde geändert"},
/*129*/	{"(null)", 0, "(null)"},
/*130*/	{"(null)", 0, "(null)"},
/*131*/	{"(null)", 0, "(null)"},
/*132*/	{"(null)", 0, "(null)"},
/*133*/	{"(null)", 0, "(null)"},
/*134*/	{"(null)", 0, "(null)"},
/*135*/	{"(null)", 0, "(null)"},
/*136*/	{"(null)", 0, "(null)"},
/*137*/	{"(null)", 0, "(null)"},
/*138*/	{"(null)", 0, "(null)"},
/*139*/	{"(null)", 0, "(null)"},
/*140*/	{"DEC001", 1, "Das DECT Mobilteil %s wurde mit der DECT Basis verbunden"},
/*141*/	{"DEC002", 1, "Die Verbindung des DECT Mobilteil %s zur DECT Basis wurde aufgehoben"},
/*142*/	{"DEC003", 1, "Das DECT Mobilteil %s hat die Verbindung zur DECT Basis verloren"},
/*143*/	{"V016", 4, "Die IP Telefonie Verbindung %s wurde erfolgreich hergestellt. IP-Adresse: %s, DNS-Server: %s, Gateway: %s"},
/*144*/	{"(null)", 0, "(null)"},
/*145*/	{"(null)", 0, "(null)"},
/*146*/	{"(null)", 0, "(null)"},
/*147*/	{"R101", 0, "Info: PADI Paket wurde vom HG gesendet"},
/*148*/	{"R102", 0, "Info: PADO Paket wurde vom HG empfangen"},
/*149*/	{"R103", 0, "Info: PADR Paket wurde vom HG gesendet"},
/*150*/	{"R104", 0, "Info: PADS Paket wurde vom HG empfangen"},
/*151*/	{"R105", 0, "Info: PADT Paket wurde vom HG empfangen"},
/*152*/	{"R106", 0, "Info: PADT Paket wurde vom HG gesendet"},
/*153*/	{"(null)", 0, "(null)"},
/*154*/	{"P001", 1, "Vom Internetanbieter zugewiesene WAN IPv6-Adresse: %s"},
/*155*/	{"P002", 1, "Vom Internetanbieter zugewiesene Gateway-IPv6-Adresse: %s"},
/*156*/	{"(null)", 0, "(null)"},
/*157*/	{"(null)", 0, "(null)"},
/*158*/	{"P005", 1, "Einwahl Router hat Präfix %s von ISP zugewiesen bekommen."},
/*159*/	{"F110", 1, "Das angeschlossene Speichermedium %s ist zu 95% voll"},
/*160*/	{"F111", 1, "Das angeschlossene Speichermedium %s ist zu 100% voll"},
/*161*/	{"F112", 6, "Die Datei-Synch./Backup des Ordners %s auf dem Gerät %s am Port %s mit dem Ziel %s auf dem Gerät %s am Port %s wurde gestartet."},
/*162*/	{"F113", 6, "Die Datei-Synch./Backup des Ordners %s auf dem Gerät %s am Port %s mit dem Ziel %s auf dem Gerät %s am Port %s wurde erfolgreich beendet"},
/*163*/	{"W010", 0, "WLAN Passwort für die Verschlüsselung wurde geändert"},
/*164*/	{"W011", 2, "WLAN-Kanal wurde geändert – Wert: %s, %s"},
/*165*/	{"W012", 1, "WLAN Übertragungsmodus wurde geändert %s"},
/*166*/	{"W013", 0, "WLAN Zeitschaltung aktiviert"},
/*167*/	{"W014", 0, "WLAN Zeitschaltung deaktiviert"},
/*168*/	{"W015", 0, "WLAN durch Zeitschaltung aktiviert"},
/*169*/	{"W016", 0, "WLAN durch Zeitschaltung deaktiviert"},
/*170*/	{"W017", 1, "Der WLAN Kanal wird aufgrund notwendiger Anpassungen zur Übertragungsverbesserung gewechselt (bisher Kanal %s)"},
/*171*/	{"W018", 1, "Der WLAN Kanal wurde aufgrund notwendiger Anpassungen zur Übertragungsverbesserung auf den Kanal %s gewechselt"},
/*172*/	{"W019", 2, "WLAN-Anmeldung an 2.4 GHz Frequenzband erfolgreich: Rechnername: %s, Mac-Adresse: %s"},
/*173*/	{"S101", 0, "Die Konfiguration des Gerätes wurde erfolgreich gespeichert."},
/*174*/	{"S102", 0, "Die Konfiguration des Gerätes wurde erfolgreich eingelesen."},
/*175*/	{"(null)", 0, "(null)"},
/*176*/	{"(null)", 0, "(null)"},
/*177*/	{"(null)", 0, "(null)"},
/*178*/	{"(null)", 0, "(null)"},
/*179*/	{"FW101", 1, "DoS (Denial of Service) Angriff %s wurde entdeckt."},
/*180*/	{"TR101", 1, "%s TR-064 Sitzung gestartet."},
/*181*/	{"AS101", 0, "Konfigurations-Service wird kontaktiert"},
/*182*/	{"AS102", 0, "Zugangsdaten wurden vom Konfigurations-Service übermittelt"},
/*183*/	{"AS103", 0, "Internet-Telefonie Daten wurden vom Konfigurations-Service übermittelt"},
/*184*/	{"(null)", 0, "(null)"},
/*185*/	{"NT101", 0, "Die IPv6 Systemzeit wurde erfolgreich aktualisiert"},
/*186*/	{"(null)", 0, "(null)"},
/*187*/	{"(null)", 0, "(null)"},
/*188*/	{"(null)", 0, "(null)"},
/*189*/	{"(null)", 0, "(null)"},
/*190*/	{"(null)", 0, "(null)"},
/*191*/	{"(null)", 0, "(null)"},
/*192*/	{"(null)", 0, "(null)"},
/*193*/	{"(null)", 0, "(null)"},
/*194*/	{"(null)", 0, "(null)"},
/*195*/	{"(null)", 0, "(null)"},
/*196*/	{"(null)", 0, "(null)"},
/*197*/	{"(null)", 0, "(null)"},
/*198*/	{"(null)", 0, "(null)"},
/*199*/	{"T101", 0, "Die Systemzeit wurde erfolgreich aktualisiert"},
/*200*/	{"(null)", 0, "(null)"},
/*201*/	{"(null)", 0, "(null)"},
/*202*/	{"H001", 10, "DHCP is active: %s %s %s %s %s %s %s %s %s %s"},
/*203*/	{"H002", 0, "DHCP has been disabled"},
/*204*/	{"A103", 0, "Configuration Service is contacted"},
/*205*/	{"A104", 0, "Access was provided by the configuration service"},
/*206*/	{"A105", 0, "Internet telephony data were transmitted from the configuration service"},
/*207*/	{"A106", 1, "Firmware update to version %s has been carried out successfully."},
/*208*/	{"A107", 0, "Configuration failed."},
/*209*/	{"(null)", 0, "(null)"},
/*210*/	{"(null)", 0, "(null)"},
/*211*/	{"(null)", 0, "(null)"},
/*212*/	{"UD102", 1, "Der Update Vorgang auf Version %s war erfolgreich."},
/*213*/	{"(null)", 0, "(null)"},
/*214*/	{"(null)", 0, "(null)"},
/*215*/	{"(null)", 0, "(null)"},
/*216*/	{"F105", 2, "Lokaler Benutzer %s, %s erfolgreich abgemeldet"},
/*217*/	{"(null)", 0, "(null)"},
/*218*/	{"W201", 1, "WPS wurde gestartet mit %s"},
/*219*/	{"W202", 1, "WPS Aktion %s"},
/*220*/	{"DH101", 3, "DHCP ist aktiv: %s %s %s"},
/*221*/	{"W006", 0, "WLAN wurde auf dem Speedport aktiviert"},
/*222*/	{"(null)", 0, "(null)"},
/*223*/	{"(null)", 0, "(null)"},
/*224*/	{"(null)", 0, "(null)"},
/*225*/	{"U101", 1, "USB Gerät %s wurde angeschlossen."},
/*226*/	{"U102", 1, "USB Gerät %s wurde entfernt."},
/*227*/	{"(null)", 0, "(null)"},
/*228*/	{"B101", 0, "Das Gerät ist neu eingeschaltet worden."},
/*229*/	{"(null)", 0, "(null)"},
/*230*/	{"B103", 0, "Es wurde ein Reboot ausgelöst."},
/*231*/	{"(null)", 0, "(null)"},
/*232*/	{"W020", 2, "WLAN-Anmeldung an 5 GHz Frequenzband erfolgreich: Rechnername: %s, Mac-Adresse: %s"},
/*233*/	{"(null)", 0, "(null)"},
/*234*/	{"(null)", 0, "(null)"},
/*235*/	{"(null)", 0, "(null)"},
/*236*/	{"(null)", 0, "(null)"},
/*237*/	{"(null)", 0, "(null)"},
/*238*/	{"(null)", 0, "(null)"},
/*239*/	{"(null)", 0, "(null)"},
/*240*/	{"S009", 0, "Schwerwiegender Fehler beim Import. Das Speedport wurde auf Werkseinstellungen zurückgesetzt."},
};

struct Log_entry log_error_hashed_EN[] =
{
/*  0*/	{"R001-56-0004", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <wrong access attributes>"},
/*  1*/	{"R001-56-0005", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <VIP not available>"},
/*  2*/	{"R001-56-0006", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <radius server not responding>"},
/*  3*/	{"R001-56-0007", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <service not supported>"},
/*  4*/	{"R001-56-0008", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <class to long>"},
/*  5*/	{"R001-56-0009", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <no domain>"},
/*  6*/	{"(null)", 0, "(null)"},
/*  7*/	{"(null)", 0, "(null)"},
/*  8*/	{"AS010", 0, "Firmware Download fehlgeschlagen."},
/*  9*/	{"AS011", 0, "Firmware Datei beschädigt."},
/* 10*/	{"V001", 1, "Anmeldung der DSL-Telefonnummer %s war nicht erfolgreich. Ursache: DNS-Fehler"},
/* 11*/	{"V002", 2, "Anmeldung der DSL-Telefonnummer %s war nicht erfolgreich. Gegenstelle meldet Ursache: %s"},
/* 12*/	{"V003", 0, "Es ist ein allgemeiner Fehler bei der IPTelefonie aufgetreten: Diese Aktion ist nicht erlaubt (SIP Fehlercode 488)"},
/* 13*/	{"V004", 1, "Anmeldung der DSL-Telefonnummer %s war nicht erfolgreich. Ursache: Gegenstelle antwortet nicht. Zeitüberschreitung."},
/* 14*/	{"V005", 2, "Abmeldung der DSL-Telefonnummer %s war nicht erfolgreich. Gegenstelle meldet Ursache: %s"},
/* 15*/	{"V006", 2, "IP-Telefonie mit %s war nicht erfolgreich. Ursache: %s"},
/* 16*/	{"V007", 0, "Es ist ein allgemeiner Fehler bei der IPTelefonie aufgetreten: Diese Aktion ist nicht möglich. (SIP Fehlercode 403)"},
/* 17*/	{"V008", 0, "Es ist ein allgemeiner Fehler bei der IPTelefonie aufgetreten: Der angerufene Teilnehmer wurde nicht gefunden (SIP Fehlercode 404)"},
/* 18*/	{"V009", 0, "Es ist ein allgemeiner Fehler bei der IPTelefonie aufgetreten: Die gewünschte SIP Funktionalität wird nicht unterstützt (SIP Fehlercode 405)"},
/* 19*/	{"T102", 0, "Die Systemzeit konnte nicht aktualisiert werden."},
/* 20*/	{"T103", 0, "Keine Antwort vom Timeserver."},
/* 21*/	{"AS007", 0, "Der Konfigurations-Server antwortet nicht."},
/* 22*/	{"AS008", 0, "Internet-Telefonie Daten konnen nicht ermittelt werden."},
/* 23*/	{"AS009", 0, "Internet-Telefonie ist nicht gebucht."},
/* 24*/	{"F114", 7, "Die Datei-Synch./Backup des Ordners %s auf dem Gerät %s am Port %s mit dem Ziel %s auf dem Gerät %s am Port %s ist gescheitert %s."},
/* 25*/	{"(null)", 0, "(null)"},
/* 26*/	{"(null)", 0, "(null)"},
/* 27*/	{"R001-56-0012", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <test user>"},
/* 28*/	{"R001-56-0013", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <user wrong domain>"},
/* 29*/	{"R001-56-0014", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <bad form>"},
/* 30*/	{"R001-56-0015", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <not in session>"},
/* 31*/	{"R001-56-0016", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <domain access disabled>"},
/* 32*/	{"R001-56-0017", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <authorization disabled>"},
/* 33*/	{"R001-56-0018", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <port limit exceeded>"},
/* 34*/	{"R001-56-0019", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <you are not allowed to connect>"},
/* 35*/	{"(null)", 0, "(null)"},
/* 36*/	{"(null)", 0, "(null)"},
/* 37*/	{"UD103", 2, "Der Update Vorgang auf Version %s war nicht erfolgreich: %s"},
/* 38*/	{"V010", 0, "Die angerufene Nummer ist unvollständig (SIP Fehlercode 484)"},
/* 39*/	{"V011", 0, "Es ist ein allgemeiner Fehler bei der IPTelefonie aufgetreten: Diese Aktion ist nicht möglich (SIP Fehlercode 491)"},
/* 40*/	{"V012", 0, "Es ist ein allgemeiner Fehler bei der IPTelefonie aufgetreten: Es ist ein Serverfehler aufgetreten (SIP Fehlercode 500)"},
/* 41*/	{"V013", 0, "Es ist ein allgemeiner Fehler bei der IPTelefonie aufgetreten: Es ist ein Serverfehler aufgetreten (SIP Fehlercode 503)"},
/* 42*/	{"(null)", 0, "(null)"},
/* 43*/	{"F001", 1, "Benutzerkonto %s wurde nach mehr als 5 erfolglosen lokalen Anmeldeversuchen für 60 Minuten gesperrt."},
/* 44*/	{"F002", 1, "Benutzerkonto %s wurde nach mehr als 5 erfolglosen externen Anmeldeversuchen für 60 Minuten gesperrt."},
/* 45*/	{"F003", 3, "Anmeldung des Benutzers %s, %s über %s nicht erfolgreich."},
/* 46*/	{"V018", 0, "PPP-Anmeldung beim IP-Telefonie-Anbieter ist fehlgeschlagen."},
/* 47*/	{"V019", 0, "PPP-Aushandlung für IP-Telefonie ist fehlgeschlagen."},
/* 48*/	{"(null)", 0, "(null)"},
/* 49*/	{"(null)", 0, "(null)"},
/* 50*/	{"S010", 0, "Die angegebene Datei ist zu groß."},
/* 51*/	{"(null)", 0, "(null)"},
/* 52*/	{"(null)", 0, "(null)"},
/* 53*/	{"(null)", 0, "(null)"},
/* 54*/	{"R001-56-0020", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <unknown dynamic ip address>"},
/* 55*/	{"R001-56-0021", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <no valid ip address>"},
/* 56*/	{"R001-56-0022", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <Der Mitbenutzer-Zugang wurde vom Hauptnutzer gesperrt>"},
/* 57*/	{"R001-56-0023", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <Ihre Zugangsdaten wurden gesperrt>."},
/* 58*/	{"R001-56-0024", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <no valid service level>"},
/* 59*/	{"R001-56-0025", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <Mit diesen Zugangsdaten ist an diesem Anschluss kein Verbindungsaufbau möglich>"},
/* 60*/	{"R001-56-0026", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <Es ist ein Fehler bei der Identifizierung Ihrer Zugangsdaten aufgetreten>"},
/* 61*/	{"R001-56-0027", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <you are not allowed to connect right now>"},
/* 62*/	{"R001-56-0028", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <Ihr T-Online Zugang wurde gesperrt>."},
/* 63*/	{"R001-56-0029", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <authorization not available>"},
/* 64*/	{"(null)", 0, "(null)"},
/* 65*/	{"(null)", 0, "(null)"},
/* 66*/	{"(null)", 0, "(null)"},
/* 67*/	{"V020", 0, "PPP-Aushandlung für IP-Telefonie ist fehlgeschlagen: Testschleife gefunden."},
/* 68*/	{"V021", 1, "Zeitüberschreitung bei der PPP-Aushandlung für IP-Telefonie. (%s)"},
/* 69*/	{"(null)", 0, "(null)"},
/* 70*/	{"(null)", 0, "(null)"},
/* 71*/	{"(null)", 0, "(null)"},
/* 72*/	{"(null)", 0, "(null)"},
/* 73*/	{"(null)", 0, "(null)"},
/* 74*/	{"(null)", 0, "(null)"},
/* 75*/	{"(null)", 0, "(null)"},
/* 76*/	{"(null)", 0, "(null)"},
/* 77*/	{"(null)", 0, "(null)"},
/* 78*/	{"(null)", 0, "(null)"},
/* 79*/	{"A001", 0, "Der Konfigurations-Service konnte nicht erreicht werden."},
/* 80*/	{"A002", 0, "Der Konfigurations-Service verweigert den Zugriff."},
/* 81*/	{"A003", 0, "Ungültiges Zertifikat am Konfigurations-Service."},
/* 82*/	{"A004", 0, "Fehlermeldung des Konfigurations-Services."},
/* 83*/	{"R001-56-0030", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <Mit den verwendeten Zugangsdaten besteht bereits eine Verbindung>"},
/* 84*/	{"R001-56-0031", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <user name bad form>"},
/* 85*/	{"R001-56-0032", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <concurrent dial in/out>"},
/* 86*/	{"R001-56-0033", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <link limit exceeded>"},
/* 87*/	{"R001-56-0034", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <Der Zugang ins Internet ist nicht möglich, da der genutzte T-Online Tarif nicht zu dem bestehenden T-DSL Anschluss passt>"},
/* 88*/	{"R001-56-0035", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <domain access revoked>"},
/* 89*/	{"(null)", 0, "(null)"},
/* 90*/	{"(null)", 0, "(null)"},
/* 91*/	{"(null)", 0, "(null)"},
/* 92*/	{"(null)", 0, "(null)"},
/* 93*/	{"IVA001", 1, "Firmware Installation auf %s nicht erfolgreich"},
/* 94*/	{"W003", 2, "WLAN Anmeldung ist gescheitert: Association-Fehler. Datenrate nicht kompatibel. Rechnername: %s, Mac-Adresse: %s"},
/* 95*/	{"W004", 2, "WLAN-Anmeldung ist gescheitert: Association-Fehler. Mac-Adresse wird nicht zugelassen. Rechnername: %s, Mac-Adresse: %s"},
/* 96*/	{"W005", 2, "WLAN-Anmeldung ist gescheitert: Autorisierung fehlgeschlagen. Rechnername: %s, Mac-Adresse: %s"},
/* 97*/	{"(null)", 0, "(null)"},
/* 98*/	{"(null)", 0, "(null)"},
/* 99*/	{"(null)", 0, "(null)"},
/*100*/	{"(null)", 0, "(null)"},
/*101*/	{"(null)", 0, "(null)"},
/*102*/	{"D001", 0, "DynDNS-Fehler: Der angegebene Domainname kann nicht aufgelöst werden."},
/*103*/	{"D002", 1, "DynDNS-Fehler: Der DynDNS-Anbieter meldet Fehler %s"},
/*104*/	{"(null)", 0, "(null)"},
/*105*/	{"(null)", 0, "(null)"},
/*106*/	{"(null)", 0, "(null)"},
/*107*/	{"A010", 0, "Firmware Download fehlgeschlagen."},
/*108*/	{"A011", 0, "Firmware Datei beschädigt."},
/*109*/	{"A012", 0, "Die persönlichen Zugangsdaten konnten nicht ermittelt werden."},
/*110*/	{"(null)", 0, "(null)"},
/*111*/	{"(null)", 0, "(null)"},
/*112*/	{"(null)", 0, "(null)"},
/*113*/	{"ZAB001", 1, "Authentifizierung des Online-Adressbuchs: %s ist fehlgeschlagen. Request-Header-Element konnte nicht übermittelt werden."},
/*114*/	{"ZAB002", 1, "Anmeldung des Online-Adressbuchs: %s ist fehlgeschlagen. Benutzername oder Passwort ist nicht korrekt."},
/*115*/	{"ZAB003", 1, "Anmeldung des Online-Adressbuchs mit den verwendeten Zugangsdaten für Telefonbuch: %s nicht möglich. Keine Berechtigung."},
/*116*/	{"ZAB004", 0, "Verbindung zum Online-Adressbuch konnte nicht aufgebaut werden. Server nicht erreichbar."},
/*117*/	{"(null)", 0, "(null)"},
/*118*/	{"A005", 0, "Ungültige Meldung des Konfigurations-Services."},
/*119*/	{"A006", 0, "Die Verbindung zum Konfigurations-Server ist abgebrochen."},
/*120*/	{"A007", 0, "Der Konfigurations-Server antwortet nicht."},
/*121*/	{"A008", 0, "DSL-Telefonie Daten können nicht ermittelt werden."},
/*122*/	{"A009", 0, "DSL-Telefonie ist nicht gebucht."},
/*123*/	{"(null)", 0, "(null)"},
/*124*/	{"(null)", 0, "(null)"},
/*125*/	{"(null)", 0, "(null)"},
/*126*/	{"(null)", 0, "(null)"},
/*127*/	{"(null)", 0, "(null)"},
/*128*/	{"R001", 0, "Anmeldung beim Internetanbieter ist fehlgeschlagen."},
/*129*/	{"R002", 0, "The Internet connection can not be made because the rate checking is enabled and the current date is not known."},
/*130*/	{"R003", 0, "The Internet connection is broken, because the tariff review is enabled and the current date is not known."},
/*131*/	{"R004", 0, "The Internet connection is briefly interrupted to forestall the forced separation of the provider."},
/*132*/	{"R005", 0, "The maximum number of port forwarding rules has been reached."},
/*133*/	{"R006", 0, "DSL is not responding (no DSLSynchronisierung)."},
/*134*/	{"R007", 0, "DSL is available (DSLSynchronisierung exists)."},
/*135*/	{"R008", 0, "DSL sync start (training)."},
/*136*/	{"R009", 0, "Internet connection has been terminated."},
/*137*/	{"(null)", 0, "(null)"},
/*138*/	{"(null)", 0, "(null)"},
/*139*/	{"(null)", 0, "(null)"},
/*140*/	{"(null)", 0, "(null)"},
/*141*/	{"(null)", 0, "(null)"},
/*142*/	{"(null)", 0, "(null)"},
/*143*/	{"UP001", 0, "UMTS-Modem-Fehler Abbruch: ‚kein Trägersignal’"},
/*144*/	{"(null)", 0, "(null)"},
/*145*/	{"(null)", 0, "(null)"},
/*146*/	{"(null)", 0, "(null)"},
/*147*/	{"OAM1001", 0, "OAM Link fault"},
/*148*/	{"OAM1002", 0, "OAM Dying gasp"},
/*149*/	{"OAM1003", 0, "OAM Critical event"},
/*150*/	{"(null)", 0, "(null)"},
/*151*/	{"U001", 1, "Der USB-Massenspeicher %s enthält kein unterstütztes Dateisystem oder hat eine ungültige Partitionstabelle."},
/*152*/	{"U002", 3, "Der angeschlossene USB-Massenspeicher %s, %s kann leider nicht verwendet werden %s."},
/*153*/	{"ZAB006", 1, "Max. Anzahl an Kontakten erreicht. Es konnten nicht alle Kontakte synchronisiert werden. (%s)."},
/*154*/	{"(null)", 0, "(null)"},
/*155*/	{"(null)", 0, "(null)"},
/*156*/	{"R010", 0, "Internet connection is established."},
/*157*/	{"R011", 0, "PPP negotiation failed."},
/*158*/	{"R012", 0, "The PPP negotiation failed: test loop found."},
/*159*/	{"R013", 0, "PPPoE error: DSL sync is lost."},
/*160*/	{"R014", 1, "PPPoE error. Wrong parameter (%s)"},
/*161*/	{"R015", 1, "PPPoE error. Incorrect service name (%s)"},
/*162*/	{"R016", 1, "PPPoE error. Illegal packet from the PPPoE server (%s)"},
/*163*/	{"R017", 1, "PPPoE error: PPPoE server reports a system error: (%s)"},
/*164*/	{"R018", 1, "PPPoE error: PPPoE server has a problem (%s)."},
/*165*/	{"R019", 1, "PPPoE error. Unknown error (%s)"},
/*166*/	{"(null)", 0, "(null)"},
/*167*/	{"(null)", 0, "(null)"},
/*168*/	{"(null)", 0, "(null)"},
/*169*/	{"(null)", 0, "(null)"},
/*170*/	{"R010-1", 0, "Internet connection for automatic configuration made."},
/*171*/	{"R010-2", 0, "Internet connection for automatic configuration made."},
/*172*/	{"(null)", 0, "(null)"},
/*173*/	{"(null)", 0, "(null)"},
/*174*/	{"(null)", 0, "(null)"},
/*175*/	{"(null)", 0, "(null)"},
/*176*/	{"(null)", 0, "(null)"},
/*177*/	{"(null)", 0, "(null)"},
/*178*/	{"(null)", 0, "(null)"},
/*179*/	{"(null)", 0, "(null)"},
/*180*/	{"(null)", 0, "(null)"},
/*181*/	{"(null)", 0, "(null)"},
/*182*/	{"(null)", 0, "(null)"},
/*183*/	{"(null)", 0, "(null)"},
/*184*/	{"(null)", 0, "(null)"},
/*185*/	{"R020", 1, "PPPoE error. Timeout (%s)"},
/*186*/	{"R021", 0, "Disconnected: The other party does not answer an LCP echo requests."},
/*187*/	{"R022", 1, "The gateway from the ISP-assigned IP address: %s"},
/*188*/	{"R023", 1, "timed out PPP Aushandlung. (%s)"},
/*189*/	{"NT102", 0, "Die IPv6 Systemzeit konnte nicht aktualisiert werden."},
/*190*/	{"NT103", 0, "Keine Antwort vom IPv6 Timeserver."},
/*191*/	{"(null)", 0, "(null)"},
/*192*/	{"(null)", 0, "(null)"},
/*193*/	{"(null)", 0, "(null)"},
/*194*/	{"(null)", 0, "(null)"},
/*195*/	{"(null)", 0, "(null)"},
/*196*/	{"P003", 0, "IPv6 Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: IPv6: <no free ip address>"},
/*197*/	{"P004", 0, "IPv6 Anmeldung beim Internetanbieter ist fehlgeschlagen."},
/*198*/	{"(null)", 0, "(null)"},
/*199*/	{"P006", 1, "Router hat kein Präfix von ISP erhalten. Fehler: %s"},
/*200*/	{"(null)", 0, "(null)"},
/*201*/	{"P008", 2, "DNSv6-Fehler: Der angegebene Domainname kann nicht von %s aufgelöst werden. Fehler: %s"},
/*202*/	{"(null)", 0, "(null)"},
/*203*/	{"AS001", 0, "Der Konfigurations-Service konnte nicht erreicht werden."},
/*204*/	{"AS002", 0, "Der Konfigurations-Service verweigert den Zugriff."},
/*205*/	{"AS003", 0, "Ungültiges Zertifikat am Konfiguratons-Service."},
/*206*/	{"AS004", 0, "Fehlermeldung des Konfigurations-Service."},
/*207*/	{"AS005", 0, "Ungültige Meldung des Konfigurations-Service."},
/*208*/	{"AS006", 0, "Die Verbindung zum Konfigurations-Server ist abgebrochen."},
/*209*/	{"H003", 0, "DHCP IP-Address-Vergabe gescheitert"},
/*210*/	{"S001", 0, "Das Import-Kennwort ist falsch."},
/*211*/	{"S002", 0, "Die angegebene Datei ist keine gültige Import-Datei."},
/*212*/	{"S003", 0, "Die Import-Datei enthält eine Landeseinstellung, die auf diesem Speedport nicht importiert werden kann."},
/*213*/	{"S004", 0, "Die Import-Datei ist nicht vorhanden oder zu klein."},
/*214*/	{"S005", 0, "Die Import-Datei passt nicht zu der aktuellen Firmware-Version."},
/*215*/	{"S006", 0, "Die Import-Datei passt nicht zu diesem Gerätetyp dem Speedport."},
/*216*/	{"S007", 0, "Die Import-Datei passt nicht zu dieser Geräte-Variante dem Speedport."},
/*217*/	{"S008", 0, "Es ist ein nicht näher spezifizierter Fehler aufgetreten."},
/*218*/	{"(null)", 0, "(null)"},
/*219*/	{"(null)", 0, "(null)"},
/*220*/	{"R001-56-0001", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <Radius Fehlermeldung>"},
/*221*/	{"R001-56-0002", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <access over this NAS not allowed>"},
/*222*/	{"R001-56-0003", 0, "Anmeldung beim Internetanbieter ist mit den verwendeten Zugangsdaten nicht möglich: <no free ip address>"},
};

int hashSearchEventDE(char* str, unsigned int len)
{
	unsigned int hash = 0;
	int i = 0;
	int t = 0;

	for(i = 0; i < len; str++, i++)
	{
		hash = hash * 551 + (*str);
	}
	i = hash % TABLE_EVENT_SIZE;
	while (strcmp(log_event_hashed_DE[i].code, str-len) != 0)
	{
		i+=121;
		if (i > TABLE_EVENT_SIZE)
			i %= TABLE_EVENT_SIZE;
		if (t++ >= _MAX_COMPARE_TIME)
			return -1;
	}
	return i;
}

int hashSearchErrorDE(char* str, unsigned int len)
{
	unsigned int hash = 0;
	int i = 0;
	int t = 0;

	for(i = 0; i < len; str++, i++)
	{
		hash = hash * 475 + (*str);
	}
	i = hash % TABLE_ERROR_SIZE;
	while (strcmp(log_error_hashed_DE[i].code, str-len) != 0)
	{
		i+=35;
		if (i > TABLE_ERROR_SIZE)
			i %= TABLE_ERROR_SIZE;
		if (t++ >= _MAX_COMPARE_TIME)
			return -1;
	}
	return i;
}

int hashSearchEventEN(char* str, unsigned int len)
{
	unsigned int hash = 0;
	int i = 0;
	int t = 0;

	for(i = 0; i < len; str++, i++)
	{
		hash = hash * 551 + (*str);
	}
	i = hash % TABLE_EVENT_SIZE;
	while (strcmp(log_event_hashed_EN[i].code, str-len) != 0)
	{
		i+=121;
		if (i > TABLE_EVENT_SIZE)
			i %= TABLE_EVENT_SIZE;
		if (t++ >= _MAX_COMPARE_TIME)
			return -1;
	}
	return i;
}

int hashSearchErrorEN(char* str, unsigned int len)
{
	unsigned int hash = 0;
	int i = 0;
	int t = 0;

	for(i = 0; i < len; str++, i++)
	{
		hash = hash * 475 + (*str);
	}
	i = hash % TABLE_ERROR_SIZE;
	while (strcmp(log_error_hashed_EN[i].code, str-len) != 0)
	{
		i+=35;
		if (i > TABLE_ERROR_SIZE)
			i %= TABLE_ERROR_SIZE;
		if (t++ >= _MAX_COMPARE_TIME)
			return -1;
	}
	return i;
}

