acs.GetParameterValues(Device.DNS.)
acs.GetParameterValues(Device.DNS.Relay.)
acs.GetParameterValues(Device.DNS.Relay.Status)
acs.GetParameterValues(Device.DNS.Relay.ForwardNumberOfEntries)
acs.GetParameterValues(Device.DNS.Relay.Forwarding.1.Status)
acs.GetParameterValues(Device.DNS.Relay.Forwarding.1.Type)
acs.execute()