acs.GetParameterValues(Device.DownloadAvailability.)
acs.GetParameterValues(Device.DownloadAvailability.Announcement.)
acs.GetParameterValues(Device.DownloadAvailability.Announcement.Status)
acs.GetParameterValues(Device.DownloadAvailability.Announcement.GroupNumberOfEntries)
acs.GetParameterValues(Device.DownloadAvailability.Announcement.Group.1.Status)
acs.execute()