acs.GetParameterValues(Device.FaultMgmt.)
acs.GetParameterValues(Device.FaultMgmt.SupportedAlarmNumberOfEntries)
acs.GetParameterValues(Device.FaultMgmt.SupportedAlarm.1.)
acs.GetParameterValues(Device.FaultMgmt.SupportedAlarm.1.EventType)
acs.GetParameterValues(Device.FaultMgmt.SupportedAlarm.1.ProbableCause)
acs.GetParameterValues(Device.FaultMgmt.SupportedAlarm.1.SpecificProblem)
acs.GetParameterValues(Device.FaultMgmt.SupportedAlarm.1.PerceivedSeverity)
acs.execute()